// Confirmation for the one irreversible act in the room.
//
// `requestUserInteraction()` is discussed in the WebMCP draft and named in our
// own dispatch — and it does not exist in the pinned packages. Zero occurrences
// in `webmcp-types@0.1.5`, zero in `@mcp-b/webmcp-polyfill@5.0.1`. That is the
// third feature in this build that is present in the spec conversation and
// absent at runtime (`exposedTo` and cross-document exposure being the others).
//
// So this does what the rest of the project does: attempt the strong path,
// fall back to one we control, and RECORD WHICH HAPPENED. The confirmation
// method travels with the act, because "a human confirmed this" means something
// different depending on what did the asking.
//
// The property that matters is not which dialog appeared. It is that the agent
// cannot ratify. It can only ask. The act that lands on the chain is the
// human's click, attributed to the human's seat through the UI door — a
// separate entry from the agent's request, which is attributed to the agent.

/** True if the browser offers the draft elicitation API. Checked at call time,
 *  never assumed: a browser shipping native WebMCP may have it when the
 *  polyfilled one does not. */
export function hasNativeElicitation() {
  const mc = globalThis.document?.modelContext;
  return typeof mc?.requestUserInteraction === 'function';
}

/** Ask the human. Resolves to what actually happened, including which mechanism
 *  did the asking, so the record can say so rather than implying a stronger
 *  ceremony than occurred. */
export async function confirmWithHuman({ title, detail }) {
  if (hasNativeElicitation()) {
    try {
      const result = await document.modelContext.requestUserInteraction({ title, detail });
      return {
        confirmed: Boolean(result?.confirmed ?? result),
        method: 'requestUserInteraction',
        note: 'the browser asked, out of the page\'s control',
        // No DOM event to fingerprint — and none needed. The whole value of
        // this path is that the page never sees the interaction, so it cannot
        // be forged by anything the page can reach.
        input: { via: 'browser-mediated; no page-observable event' },
      };
    } catch (err) {
      // Fall through to the in-page dialog rather than failing the act: a
      // confirmation that errors must not become an implicit "yes".
      return inPageConfirm({ title, detail, note: `native elicitation failed: ${err?.message ?? err}` });
    }
  }
  return inPageConfirm({
    title,
    detail,
    note: 'requestUserInteraction() is not available in this browser; the page asked instead',
  });
}

/** A real modal the host must actually click. Not `window.confirm` — that
 *  cannot be styled, cannot be screenshotted usefully, and in some embedded
 *  browsers is suppressed entirely, which would turn a missing dialog into a
 *  silent refusal nobody could see. */
// There is ONE dialog element, so there can be one confirmation at a time.
//
// Two overlapping `ratify_ruling` calls actually happened in the judge
// environment: the first blocked on the modal, the agent's harness timed it out,
// and it called again. Without this guard both would `showModal()` on the same
// element and both would attach listeners — so a single click could resolve two
// pending ratifications, and the room would record a decision the human made
// once as though they had made it twice.
//
// A second request is REFUSED rather than queued. Queueing an irreversible act
// behind a dialog the human has already answered is how one deliberate click
// becomes two acts; refusing is the answer that cannot surprise anyone, and the
// refusal lands on the chain like any other outcome.
let confirmationOpen = false;

/** Raw properties of whatever pressed the button. RAW, and deliberately never
 *  labelled "human" or "synthetic" — the whole finding here is that the page
 *  cannot tell, so a field claiming to have told would be the same over-claim
 *  in a smaller box. A reader gets the values and draws their own conclusion.
 *
 *  What the values mean, stated once so the receipt does not have to argue:
 *   - `isTrusted: false`  → generated by page script (`element.click()`).
 *   - `isTrusted: true` with no pointer/mouse prelude and zeroed coordinates
 *     → dispatched through the browser's own input pipeline (automation
 *     driver, accessibility action). **Indistinguishable from a person at the
 *     DOM surface**, which is the point.
 *   - `isTrusted: true`, prelude present, real coordinates, `detail: 1`
 *     → consistent with a person, and still only consistent with.
 *
 *  ONE FIELD IS LOAD-BEARING AND THE REST ARE DECORATION, which was worth
 *  finding out before shipping. Testing this instrument, page script forged
 *  every field except one: a `pointerdown:mouse+mousedown` prelude, plausible
 *  `screen`/`client` coordinates and `detail: 1` were all produced by
 *  `dispatchEvent`, and the receipt recorded them as though a hand had moved.
 *  Only `isTrusted` stayed `false`, because a page cannot forge it.
 *
 *  So: `isTrusted` is the measurement. The prelude and the coordinates
 *  distinguish careless script from careful script and nothing else — they add
 *  no evidence against an automation driver, which produces genuine ones. They
 *  are kept because a careless forgery is still worth catching, and because a
 *  reader deserves to see what the page saw. They must not be read as
 *  corroboration. */
function describeInput(ev, prelude) {
  if (!ev) return { via: 'dialog cancel (Escape or programmatic close)', prelude };
  return {
    isTrusted: ev.isTrusted,
    detail: ev.detail,
    screen: [ev.screenX, ev.screenY],
    client: [ev.clientX, ev.clientY],
    prelude: prelude.length ? prelude.join('+') : 'none',
  };
}

function inPageConfirm({ title, detail, note }) {
  if (confirmationOpen) {
    return Promise.resolve({
      confirmed: false,
      method: 'refused',
      note: 'another confirmation is already open — a second request cannot be answered by the same click',
    });
  }
  confirmationOpen = true;
  return new Promise((resolve) => {
    const dialog = document.getElementById('confirm-dialog');
    document.getElementById('confirm-title').textContent = title;
    document.getElementById('confirm-detail').textContent = detail;
    document.getElementById('confirm-note').textContent = note;

    // What preceded the click. A person pressing a button generates a pointer
    // and mouse press first; a scripted `.click()` generates neither. Recorded
    // as observation, not verdict.
    let prelude = [];
    const notePrelude = (e) => { prelude.push(`${e.type}${e.pointerType ? `:${e.pointerType}` : ''}`); };

    const done = (confirmed, ev) => {
      confirmationOpen = false;
      dialog.close();
      yes.removeEventListener('click', onYes);
      no.removeEventListener('click', onNo);
      dialog.removeEventListener('cancel', onCancel);
      for (const t of ['pointerdown', 'mousedown']) {
        yes.removeEventListener(t, notePrelude);
        no.removeEventListener(t, notePrelude);
      }
      resolve({ confirmed, method: 'in-page dialog', note, input: describeInput(ev, prelude) });
    };

    const yes = document.getElementById('confirm-yes');
    const no = document.getElementById('confirm-no');
    const onYes = (e) => done(true, e);
    const onNo = (e) => done(false, e);
    // Dismissing with Escape is a refusal, never a default yes.
    const onCancel = () => done(false, null);

    for (const t of ['pointerdown', 'mousedown']) {
      yes.addEventListener(t, notePrelude);
      no.addEventListener(t, notePrelude);
    }
    yes.addEventListener('click', onYes);
    no.addEventListener('click', onNo);
    dialog.addEventListener('cancel', onCancel);
    dialog.showModal();
  });
}
